import {Inter} from "next/font/google";
import "./globals.css";
import Meta from "@/components/global/Meta";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Meta />
      <body className={`${inter.className} max-w-[1258px] mx-auto sm:px-6`}>
        <main className=" pt-6 flex flex-col gap-8">{children}</main>
      </body>
    </html>
  );
}
